language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  apt:
    packages:
      - build-essential
      - libxslt-dev
      - libzip-dev
      - libldap2-dev
      - libsasl2-dev
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_ACCESS_KEY
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
before_script:
  - sleep 10
  - psql -c 'create database test_db;' -U postgres
  - sleep 10
  - ./odoo-bin start -i base -d test_db &
  - sleep 40
script:
  - cd acceptance && behave --stage=ui
cache: pip
